# Site settings
title: MYAIEXP
author: rozeappletreeğŸŠ
author_avatar: /images/header.jpg
email: alias@domain.tld
description: ç”Ÿå‘½ä¸æ­¢ï¼ŒæŠ˜è…¾ä¸æ¯ 
url: "https://dongyadoit.com"
domain: "http://dongyadoit.com"
github_username: dongyado
github_site_repo: dongyado/dongyado.github.io
disqus: rozeappletreeğŸŠ


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    syntax_highlighter: rouge
    extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]

sass:
    style: :compressed
    sass_dir: _sass

permalink: pretty
excerpt_separator: "<!-- more -->"

# path
categories_path: categories/
tags_path: tags/


gems:
  - jekyll-sitemap
